[package]
name = "selene-db-gql-fuzz"
version = "2.0.0-alpha.1"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
selene-gql = { package = "selene-db-gql", path = "..", version = "2.0.0-alpha.1" }

[[bin]]
name = "parse_gql"
path = "fuzz_targets/parse_gql.rs"
test = false
doc = false
bench = false

[[bin]]
name = "round_trip"
path = "fuzz_targets/round_trip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_many_gql"
path = "fuzz_targets/parse_many_gql.rs"
test = false
doc = false
bench = false
