[package]
name = "selene-testing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[features]
default = []

[lints]
workspace = true

[dependencies]
selene-core = { path = "../selene-core", version = "1.0.0" }
selene-gql = { path = "../selene-gql", version = "1.0.0" }
selene-graph = { path = "../selene-graph", version = "1.0.0" }
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
