[package]
name = "selene-graph"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
autobenches = false

[dependencies]
selene-core = { path = "../selene-core", version = "0.0.0" }
selene-persist.workspace = true
arc-swap.workspace = true
parking_lot.workspace = true
imbl.workspace = true
jiff.workspace = true
roaring.workspace = true
smallvec.workspace = true
triomphe.workspace = true
serde.workspace = true
postcard.workspace = true
rkyv.workspace = true
thiserror.workspace = true
miette.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
criterion.workspace = true
iai-callgrind.workspace = true
proptest.workspace = true
rstest.workspace = true
selene-testing = { path = "../selene-testing", version = "0.0.0" }

[[bench]]
name = "single_graph"
harness = false

[[bench]]
name = "bulk_mutation"
harness = false

[[bench]]
name = "concurrent_read"
harness = false

[[bench]]
name = "bfs"
harness = false

[[bench]]
name = "iai_gates"
harness = false

[lints]
workspace = true
