//! Implementation-defined Markdown report generation.

use std::fmt::Write as _;

use crate::{
    DecisionStability, DecisionVisibility, ImplementationDefinedDecision,
    ImplementationDefinedValue, ValidatedProfile,
};

pub(super) fn render(profile: &ValidatedProfile) -> String {
    let source = profile.profile();
    let mut records = source
        .implementation_defined_choices
        .iter()
        .collect::<Vec<_>>();
    records.sort_by_key(|record| record.runtime_order);
    let mut output = format!(
        "<!-- @generated by selene-profile; generator-version: {}; profile-hash: {} -->\n\n\
         # GQL implementation-defined profile\n\n\
         This report is a complete ID inventory and implementation audit aid for the selected Selene profile. It paraphrases Selene decisions only; Annex B remains in the standard. This report is not normative text and does not make a conformance claim.\n\n\
         Profile: `{}`. Release claimable: **{}**.\n\n\
         | ID | Topic | Applies | Disposition or value | Rationale | Evidence |\n\
         |---|---|---|---|---|---|\n",
        source.generator_version,
        profile.hash(),
        escape(&source.profile_id),
        source.release_claimable,
    );
    for record in records {
        let applies = profile
            .applicability(record.applicability.as_str())
            .expect("validated applicability");
        let (disposition, rationale) = decision(&record.decision);
        let evidence = record
            .evidence
            .iter()
            .map(|id| format!("`{}`", id.as_str()))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "| {} | {} | {} (`{}`) | {} | {} | {} |",
            record.id.as_str(),
            escape(&record.topic),
            if applies { "yes" } else { "no" },
            record.applicability.as_str(),
            escape(&disposition),
            escape(&rationale),
            evidence,
        )
        .expect("String writes cannot fail");
    }
    output
}

fn decision(decision: &ImplementationDefinedDecision) -> (String, String) {
    match decision {
        ImplementationDefinedDecision::Selected {
            value,
            rationale,
            stability,
            visibility,
        } => (
            format!(
                "selected: {}; {}; {}",
                value_text(value),
                stability_text(*stability),
                visibility_text(*visibility)
            ),
            rationale.clone(),
        ),
        ImplementationDefinedDecision::Pending { owner, reason } => {
            (format!("pending: {owner}"), reason.clone())
        }
        ImplementationDefinedDecision::NotApplicable { reason } => {
            ("not applicable".to_owned(), reason.clone())
        }
    }
}

fn value_text(value: &ImplementationDefinedValue) -> String {
    match value {
        ImplementationDefinedValue::Boolean { value } => value.to_string(),
        ImplementationDefinedValue::UnsignedInteger { value } => value.to_string(),
        ImplementationDefinedValue::Identifier { value }
        | ImplementationDefinedValue::String { value } => value.clone(),
        ImplementationDefinedValue::OrderedIdentifierList { value }
        | ImplementationDefinedValue::OrderedStringList { value } => value.join("; "),
    }
}

const fn stability_text(value: DecisionStability) -> &'static str {
    match value {
        DecisionStability::Stable => "stable",
        DecisionStability::Provisional => "provisional",
    }
}

const fn visibility_text(value: DecisionVisibility) -> &'static str {
    match value {
        DecisionVisibility::Public => "public",
        DecisionVisibility::Embedder => "embedder",
        DecisionVisibility::Internal => "internal",
    }
}

fn escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "\\|")
        .replace(['\r', '\n'], " ")
}
