//! Deterministic checked-in Rust and Markdown generation.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::model::RuntimeSupport;
use crate::{ProfileError, ValidatedProfile, load_profile};

const SOURCE: &str = "spec/gql-profile/profile.json";

/// Render every canonical source and generated output for a validated profile.
pub fn render_outputs(profile: &ValidatedProfile) -> Result<Vec<(PathBuf, String)>, ProfileError> {
    let source = format!("{}\n", serde_json::to_string_pretty(profile.profile())?);
    Ok(vec![
        (PathBuf::from(SOURCE), source),
        (
            PathBuf::from("crates/selene-profile/src/generated/mod.rs"),
            render_mod(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/feature_ids.rs"),
            render_feature_ids(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/feature_data.rs"),
            render_feature_data(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/annex_b.rs"),
            render_annex_b(profile),
        ),
        (
            PathBuf::from("spec/gql-profile/registry.md"),
            render_markdown(profile),
        ),
    ])
}

/// Regenerate checked-in source, Rust, and Markdown from the profile JSON.
pub fn write_repository(root: &Path) -> Result<(), ProfileError> {
    let profile = load_profile(&root.join(SOURCE))?;
    for (relative, content) in render_outputs(&profile)? {
        let path = root.join(relative);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|source| ProfileError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        std::fs::write(&path, content).map_err(|source| ProfileError::Io { path, source })?;
    }
    Ok(())
}

/// Fail when a checked-in source or generated output is stale.
pub fn check_repository(root: &Path) -> Result<(), ProfileError> {
    let profile = load_profile(&root.join(SOURCE))?;
    for (relative, expected) in render_outputs(&profile)? {
        let path = root.join(&relative);
        let actual = std::fs::read_to_string(&path).map_err(|source| ProfileError::Io {
            path: path.clone(),
            source,
        })?;
        if actual != expected {
            return Err(ProfileError::Stale(relative));
        }
    }
    Ok(())
}

fn header(profile: &ValidatedProfile) -> String {
    format!(
        "// @generated by `cargo run -p selene-db-profile --bin selene-profile -- --write`; profile-hash: {}\n\n",
        profile.hash()
    )
}

fn render_mod(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "mod annex_b;\nmod feature_data;\nmod feature_ids;\n\n\
         pub use annex_b::ANNEX_B_REGISTER;\n\
         pub use feature_data::{NOT_SUPPORTED_RATIONALE, REFERENCED_FEATURES, SUPPORTED_FEATURES};\n\n",
    );
    writeln!(
        output,
        "/// Source profile format version.\npub const PROFILE_FORMAT_VERSION: u32 = {};",
        profile.profile().format_version
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "/// BLAKE3 hash of the canonical semantic profile.\npub const PROFILE_HASH: &str = {:?};",
        profile.hash()
    )
    .expect("writing to String cannot fail");
    output
}

fn render_feature_ids(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str("use crate::runtime::FeatureId;\n\nimpl FeatureId {\n");
    let mut entries = profile
        .profile()
        .features
        .iter()
        .map(|item| (item.id.as_str(), item.name.as_str()))
        .chain(
            profile
                .profile()
                .implementation_extensions
                .iter()
                .map(|item| (item.id.as_str(), item.name.as_str())),
        )
        .collect::<Vec<_>>();
    entries.sort_unstable();
    for (id, name) in entries {
        writeln!(
            output,
            "    #[doc = {:?}]\n    pub const {id}: FeatureId = FeatureId::new({id:?});",
            format!("`{name}`")
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("}\n");
    output
}

fn render_feature_data(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "use crate::runtime::FeatureId;\n\n\
         /// Every feature and extension currently referenced by runtime consumers.\n\
         #[rustfmt::skip]\n\
         pub const REFERENCED_FEATURES: &[(FeatureId, &str)] = &[\n",
    );
    let mut entries = profile
        .profile()
        .features
        .iter()
        .map(|item| {
            (
                item.runtime_order,
                item.id.as_str(),
                item.name.as_str(),
                item.runtime_support,
                item.unsupported_rationale.as_str(),
            )
        })
        .chain(
            profile
                .profile()
                .implementation_extensions
                .iter()
                .map(|item| {
                    (
                        item.runtime_order,
                        item.id.as_str(),
                        item.name.as_str(),
                        item.runtime_support,
                        item.unsupported_rationale.as_str(),
                    )
                }),
        )
        .collect::<Vec<_>>();
    entries.sort_by_key(|item| item.0);
    for (_, id, name, _, _) in &entries {
        writeln!(output, "    (FeatureId::{id}, {name:?}),")
            .expect("writing to String cannot fail");
    }
    output.push_str(
        "];\n\n/// Existing runtime-supported feature and extension set.\n\
         #[rustfmt::skip]\n\
         pub const SUPPORTED_FEATURES: &[FeatureId] = &[\n",
    );
    for id in &profile.profile().supported_feature_order {
        writeln!(output, "    FeatureId::{},", id.as_str()).expect("writing to String cannot fail");
    }
    output.push_str(
        "];\n\n/// Exact runtime rejection rationales.\n\
         #[rustfmt::skip]\n\
         pub const NOT_SUPPORTED_RATIONALE: &[(FeatureId, &str)] = &[\n",
    );
    for feature_id in &profile.profile().unsupported_feature_order {
        let feature = profile
            .profile()
            .features
            .iter()
            .find(|item| item.id == *feature_id)
            .expect("unsupported compatibility references were validated");
        writeln!(
            output,
            "    (FeatureId::{}, {:?}),",
            feature.id.as_str(),
            feature.unsupported_rationale
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("];\n");
    output
}

fn render_annex_b(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "use crate::runtime::{AnnexBId, ImplDefinedChoice};\n\n\
         /// Partial implementation-defined inventory inherited from the 1.x register.\n\
         #[rustfmt::skip]\n\
         pub const ANNEX_B_REGISTER: &[(AnnexBId, ImplDefinedChoice)] = &[\n",
    );
    let mut choices = profile
        .profile()
        .implementation_defined_choices
        .iter()
        .collect::<Vec<_>>();
    choices.sort_by_key(|item| item.runtime_order);
    for item in choices {
        writeln!(
            output,
            "    (AnnexBId::new({:?}), ImplDefinedChoice {{ choice: {:?}, settled_in: {:?} }}),",
            item.id.as_str(),
            item.choice,
            item.settled_in
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("];\n");
    output
}

fn render_markdown(profile: &ValidatedProfile) -> String {
    let mut output = format!(
        "<!-- @generated by selene-profile; profile-hash: {} -->\n\n\
         # GQL profile registry\n\n\
         Profile `{}` uses source format {}. Runtime support below preserves the pre-M01 compatibility surface; it is separate from formal claim state.\n\n\
         ## ISO optional features\n\n\
         | ID | Name | Runtime | Claim | Rationale |\n\
         |---|---|---|---|---|\n",
        profile.hash(),
        markdown(&profile.profile().profile_id),
        profile.profile().format_version
    );
    for item in &profile.profile().features {
        writeln!(
            output,
            "| {} | {} | {} | {} | {} |",
            item.id.as_str(),
            markdown(&item.name),
            enum_name(item.runtime_support),
            claim_name(item.claim_state),
            markdown(&item.unsupported_rationale)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str(
        "\n## Implementation extensions\n\n\
         These IDs are not ISO optional features.\n\n\
         | ID | Name | Runtime |\n|---|---|---|\n",
    );
    for item in &profile.profile().implementation_extensions {
        writeln!(
            output,
            "| {} | {} | {} |",
            item.id.as_str(),
            markdown(&item.name),
            enum_name(item.runtime_support)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str(
        "\n## Partial implementation-defined inventory\n\n\
         This table preserves the existing incomplete Annex B register. M01-PR03 owns completeness and semantic correction.\n\n\
         | ID | Choice | Existing owner |\n|---|---|---|\n",
    );
    for item in &profile.profile().implementation_defined_choices {
        writeln!(
            output,
            "| {} | {} | {} |",
            item.id.as_str(),
            markdown(&item.choice),
            markdown(&item.settled_in)
        )
        .expect("writing to String cannot fail");
    }
    writeln!(
        output,
        "\nDirect implication edges: {}. Implementation-dependent notes: {}. Evidence references: {}.",
        profile.profile().implications.len(),
        profile.profile().implementation_dependent_notes.len(),
        profile.profile().evidence.len()
    )
    .expect("writing to String cannot fail");
    output
}

fn enum_name(value: RuntimeSupport) -> &'static str {
    match value {
        RuntimeSupport::Supported => "supported",
        RuntimeSupport::Unsupported => "unsupported",
        RuntimeSupport::Referenced => "referenced",
    }
}

fn claim_name(value: crate::ClaimState) -> &'static str {
    match value {
        crate::ClaimState::Unsupported => "unsupported",
        crate::ClaimState::ImplementedUnclaimed => "implemented_unclaimed",
        crate::ClaimState::ClaimedPendingEvidence => "claimed_pending_evidence",
        crate::ClaimState::Claimed => "claimed",
    }
}

fn markdown(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "\\|")
        .replace(['\r', '\n'], " ")
}
