//! Deterministic checked-in Rust and Markdown generation.

mod annex_b;
mod report;
mod session_defaults;

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::model::RuntimeSupport;
use crate::{ProfileError, ValidatedProfile, load_profile};

const SOURCE: &str = "spec/gql-profile/profile.json";

/// Render every canonical source and generated output for a validated profile.
pub fn render_outputs(profile: &ValidatedProfile) -> Result<Vec<(PathBuf, String)>, ProfileError> {
    let source = format!("{}\n", serde_json::to_string_pretty(profile.profile())?);
    let mut outputs = vec![
        (PathBuf::from(SOURCE), source),
        (
            PathBuf::from("crates/selene-profile/src/generated/mod.rs"),
            render_mod(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/feature_ids.rs"),
            render_feature_ids(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/feature_data.rs"),
            render_feature_data(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/annex_b.rs"),
            annex_b::render_index(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/profile_data.rs"),
            render_profile_data(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/session_defaults.rs"),
            session_defaults::render(profile)?,
        ),
        (
            PathBuf::from("spec/gql-profile/registry.md"),
            render_markdown(profile),
        ),
        (
            PathBuf::from("docs/gql/conformance/features.md"),
            render_claim_matrix(profile),
        ),
        (
            PathBuf::from("docs/gql/conformance/implementation-defined.md"),
            report::render(profile),
        ),
    ];
    outputs.extend(annex_b::render_categories(profile));
    Ok(outputs)
}

/// Regenerate checked-in source, Rust, and Markdown from the profile JSON.
pub fn write_repository(root: &Path) -> Result<(), ProfileError> {
    let profile = load_profile(&root.join(SOURCE))?;
    for (relative, content) in render_outputs(&profile)? {
        let path = root.join(relative);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|source| ProfileError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        std::fs::write(&path, content).map_err(|source| ProfileError::Io { path, source })?;
    }
    Ok(())
}

/// Fail when a checked-in source or generated output is stale.
pub fn check_repository(root: &Path) -> Result<(), ProfileError> {
    let profile = load_profile(&root.join(SOURCE))?;
    for (relative, expected) in render_outputs(&profile)? {
        let path = root.join(&relative);
        let actual = std::fs::read_to_string(&path).map_err(|source| ProfileError::Io {
            path: path.clone(),
            source,
        })?;
        if actual != expected {
            return Err(ProfileError::Stale(relative));
        }
    }
    Ok(())
}

fn header(profile: &ValidatedProfile) -> String {
    format!(
        "// @generated by `cargo run -p selene-db-profile --bin selene-profile -- --write`; generator-version: {}; profile-hash: {}\n\n",
        profile.profile().generator_version,
        profile.hash(),
    )
}

fn render_mod(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "mod annex_b;\nmod annex_b_ia;\nmod annex_b_id;\nmod annex_b_ie;\nmod annex_b_il;\nmod annex_b_is;\nmod annex_b_iv;\nmod annex_b_iw;\nmod feature_data;\nmod feature_ids;\nmod profile_data;\nmod session_defaults;\n\n\
         pub use annex_b::{\n    \
         ANNEX_B_CATEGORY_COUNTS, ANNEX_B_LOOKUP_TEST_VECTORS, annex_b_by_id, annex_b_records,\n\
         };\n\
         pub use annex_b_ia::ANNEX_B_IA;\n\
         pub use annex_b_id::ANNEX_B_ID;\n\
         pub use annex_b_ie::ANNEX_B_IE;\n\
         pub use annex_b_il::ANNEX_B_IL;\n\
         pub use annex_b_is::ANNEX_B_IS;\n\
         pub use annex_b_iv::ANNEX_B_IV;\n\
         pub use annex_b_iw::ANNEX_B_IW;\n\
         pub(crate) use feature_data::{CAPABILITY_RECORDS, capability_by_id};\n\
         pub use profile_data::{DIRECT_SELECTED_FEATURES, TARGET_FEATURE_CLOSURE};\n\
         pub(crate) use session_defaults::SESSION_DEFAULTS;\n\n",
    );
    writeln!(
        output,
        "/// Source profile format version.\npub const PROFILE_FORMAT_VERSION: u32 = {};",
        profile.profile().format_version
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "/// Source profile generator version.\npub const PROFILE_GENERATOR_VERSION: u32 = {};",
        profile.profile().generator_version
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "/// Stable target profile identifier.\npub const PROFILE_ID: &str = {:?};",
        profile.profile().profile_id
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "/// Whether the target profile is release-claimable.\npub const RELEASE_CLAIMABLE: bool = {};",
        profile.profile().release_claimable
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "/// BLAKE3 hash of the canonical semantic profile.\npub const PROFILE_HASH: &str = {:?};",
        profile.hash()
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "\npub(crate) const PROFILE_IDENTITY: crate::runtime::ProfileIdentity =\n    crate::runtime::ProfileIdentity::new(\n        PROFILE_ID,\n        PROFILE_FORMAT_VERSION,\n        PROFILE_GENERATOR_VERSION,\n        PROFILE_HASH,\n    );"
    )
    .expect("writing to String cannot fail");
    output
}

fn render_feature_ids(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str("use crate::runtime::FeatureId;\n\nimpl FeatureId {\n");
    let mut entries = profile
        .profile()
        .features
        .iter()
        .map(|item| (item.id.as_str(), item.name.as_str()))
        .chain(
            profile
                .profile()
                .implementation_extensions
                .iter()
                .map(|item| (item.id.as_str(), item.name.as_str())),
        )
        .collect::<Vec<_>>();
    entries.sort_unstable();
    for (id, name) in entries {
        writeln!(
            output,
            "    #[doc = {:?}]\n    pub const {id}: FeatureId = FeatureId::new({id:?});",
            format!("`{name}`")
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("}\n");
    output
}

fn render_feature_data(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "use crate::runtime::{\n    CapabilityClaimState, CapabilityRecord, CapabilityStatus, EvidenceStatus, FeatureId,\n    FeatureSurface, FlaggerStatus, ProfileRelation,\n};\n\n\
         #[rustfmt::skip]\n\
         pub(crate) const CAPABILITY_RECORDS: &[CapabilityRecord] = &[\n",
    );
    let direct = profile
        .profile()
        .selected_features
        .iter()
        .map(|id| id.as_str())
        .collect::<BTreeSet<_>>();
    let closure = target_closure(profile);
    let mut entries = profile
        .profile()
        .features
        .iter()
        .map(|item| {
            (
                item.runtime_order,
                item.id.as_str(),
                item.name.as_str(),
                item.runtime_support,
                Some(item.claim_state),
                item.unsupported_rationale.as_str(),
                item.evidence.len(),
            )
        })
        .chain(
            profile
                .profile()
                .implementation_extensions
                .iter()
                .map(|item| {
                    (
                        item.runtime_order,
                        item.id.as_str(),
                        item.name.as_str(),
                        item.runtime_support,
                        None,
                        item.unsupported_rationale.as_str(),
                        item.evidence.len(),
                    )
                }),
        )
        .collect::<Vec<_>>();
    entries.sort_by_key(|item| item.0);
    let mut lookup_entries = Vec::with_capacity(entries.len());
    for (index, (_, id, name, status, claim, rationale, evidence_count)) in
        entries.into_iter().enumerate()
    {
        lookup_entries.push((id, index));
        let rationale = if status == RuntimeSupport::Referenced && rationale.is_empty() {
            format!("{name} is referenced by the profile but is not runtime-supported.")
        } else {
            rationale.to_owned()
        };
        let is_iso = claim.is_some();
        let is_direct = is_iso && direct.contains(id);
        let (surface, relation, claim) = match claim {
            Some(claim) => (
                "Iso",
                if is_direct {
                    "Direct"
                } else if closure.contains(id) {
                    "Implied"
                } else {
                    "Unselected"
                },
                claim_name_rust(claim),
            ),
            None => ("Extension", "Extension", "NotApplicable"),
        };
        let flagger_status = if flagger_accepted(is_iso, is_direct, status) {
            "Accepted"
        } else {
            "Rejected"
        };
        writeln!(
            output,
            "    CapabilityRecord {{ id: FeatureId::{id}, name: {name:?}, status: CapabilityStatus::{}, flagger_status: FlaggerStatus::{flagger_status}, surface: FeatureSurface::{surface}, profile_relation: ProfileRelation::{relation}, claim_state: CapabilityClaimState::{claim}, evidence_status: EvidenceStatus::{}, evidence_count: {evidence_count}, non_support_rationale: {rationale:?} }},",
            runtime_support_rust(status),
            if evidence_count == 0 {
                "Incomplete"
            } else {
                "Present"
            },
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("];\n\npub(crate) fn capability_by_id(id: &str) -> Option<&'static CapabilityRecord> {\n    match id {\n");
    for (id, index) in lookup_entries {
        writeln!(
            output,
            "        {id:?} => Some(&CAPABILITY_RECORDS[{index}]),"
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("        _ => None,\n    }\n}\n");
    output
}

fn render_profile_data(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "use crate::runtime::FeatureId;\n\n\
         /// ISO features selected directly by the target profile.\n\
         #[rustfmt::skip]\n\
         pub const DIRECT_SELECTED_FEATURES: &[FeatureId] = &[\n",
    );
    for id in &profile.profile().selected_features {
        writeln!(output, "    FeatureId::{},", id.as_str()).expect("writing to String cannot fail");
    }
    output.push_str(
        "];\n\n/// Direct selections plus every reachable Table 10 dependency.\n\
         #[rustfmt::skip]\n\
         pub const TARGET_FEATURE_CLOSURE: &[FeatureId] = &[\n",
    );
    for id in profile.closure.closure_for(
        profile
            .profile()
            .selected_features
            .iter()
            .map(|item| item.as_str()),
    ) {
        writeln!(output, "    FeatureId::{id},").expect("writing to String cannot fail");
    }
    output.push_str("];\n");
    output
}

fn render_markdown(profile: &ValidatedProfile) -> String {
    let mut output = format!(
        "<!-- @generated by selene-profile; profile-hash: {} -->\n\n\
         # GQL profile registry\n\n\
         Profile `{}` uses source format {} and generator version {}. Release claimable: **{}**. Flagger admission, runtime support, formal claim state, and evidence are separate generated dimensions.\n\n\
         ## ISO optional features\n\n\
         | ID | Name | Flagger | Runtime | Claim | Rationale |\n\
         |---|---|---|---|---|---|\n",
        profile.hash(),
        markdown(&profile.profile().profile_id),
        profile.profile().format_version,
        profile.profile().generator_version,
        profile.profile().release_claimable,
    );
    for item in &profile.profile().features {
        writeln!(
            output,
            "| {} | {} | {} | {} | {} | {} |",
            item.id.as_str(),
            markdown(&item.name),
            flagger_status_name(
                true,
                profile
                    .profile()
                    .selected_features
                    .iter()
                    .any(|selected| selected == &item.id),
                item.runtime_support,
            ),
            enum_name(item.runtime_support),
            claim_name(item.claim_state),
            markdown(&item.unsupported_rationale)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str(
        "\n## Implementation extensions\n\n\
         These IDs are not ISO optional features.\n\n\
         | ID | Name | Flagger | Runtime |\n|---|---|---|---|\n",
    );
    for item in &profile.profile().implementation_extensions {
        writeln!(
            output,
            "| {} | {} | {} | {} |",
            item.id.as_str(),
            markdown(&item.name),
            flagger_status_name(false, false, item.runtime_support),
            enum_name(item.runtime_support)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str(
        "\n## Implementation-defined inventory\n\n\
         The complete 117-ID audit report is generated at [`docs/gql/conformance/implementation-defined.md`](../../docs/gql/conformance/implementation-defined.md). Annex B is used as an inventory aid; the report is not normative text or a conformance claim.\n",
    );
    writeln!(
        output,
        "\nDirect selected features: {}. Complete target closure: {}. Direct implication edges: {}. Implementation-dependent notes: {}. Evidence references: {}.",
        profile.profile().selected_features.len(),
        target_closure(profile).len(),
        profile.profile().implications.len(),
        profile.profile().implementation_dependent_notes.len(),
        profile.profile().evidence.len()
    )
    .expect("writing to String cannot fail");
    output
}

fn render_claim_matrix(profile: &ValidatedProfile) -> String {
    let source = profile.profile();
    let closure = target_closure(profile);
    let implication_endpoint_count = source
        .implications
        .iter()
        .flat_map(|edge| [edge.source.as_str(), edge.target.as_str()])
        .collect::<BTreeSet<_>>()
        .len();
    let claimability = if source.release_claimable {
        "This target is release-claimable under the validated profile contract. Runtime support and formal claim state are reported independently; this status does not establish minimum- or selected-profile conformance."
    } else {
        "This target is not release-claimable. Runtime support and formal claim state are reported independently."
    };
    let features = source
        .features
        .iter()
        .map(|feature| (feature.id.as_str(), feature))
        .collect::<std::collections::BTreeMap<_, _>>();
    let mut output = format!(
        "<!-- @generated by selene-profile; generator-version: {}; profile-hash: {} -->\n\n\
         # GQL conformance features\n\n\
         | Field | Value |\n|---|---|\n\
         | Target profile | `{}` |\n\
         | Source format | {} |\n\
         | Generator version | {} |\n\
         | Profile hash | `{}` |\n\
         | Release claimable | **{}** |\n\
         | Direct selections | {} |\n\
         | Complete Table 10 closure | {} |\n\n\
         {claimability}\n\n\
         ## Direct Table 10 implications\n\n\
         | Source | Dependency | Provenance |\n|---|---|---|\n",
        source.generator_version,
        profile.hash(),
        markdown(&source.profile_id),
        source.format_version,
        source.generator_version,
        profile.hash(),
        source.release_claimable,
        source.selected_features.len(),
        closure.len(),
    );
    let clauses = source
        .clause_anchors
        .iter()
        .map(|anchor| (anchor.id.as_str(), anchor.citation.as_str()))
        .collect::<std::collections::BTreeMap<_, _>>();
    for edge in &source.implications {
        let provenance = edge
            .clause_anchors
            .iter()
            .map(|id| clauses[id.as_str()])
            .collect::<Vec<_>>()
            .join("; ");
        writeln!(
            output,
            "| {} | {} | {} |",
            edge.source.as_str(),
            edge.target.as_str(),
            markdown(&provenance)
        )
        .expect("writing to String cannot fail");
    }

    output.push_str(
        "\n## Claim matrix and dependency paths\n\n\
         | Source | Feature | Relation | Path | Runtime | Claim | Evidence |\n\
         |---|---|---|---|---|---|---|\n",
    );
    for selected in &source.selected_features {
        write_matrix_row(
            &mut output,
            selected.as_str(),
            selected.as_str(),
            "direct selection",
            &[selected.as_str().to_owned()],
            features[selected.as_str()],
        );
        for dependency in profile.closure.dependencies(selected.as_str()) {
            let relation = match profile.closure.relation(selected.as_str(), dependency) {
                Some(crate::closure::DependencyRelation::Direct) => "direct dependency",
                Some(crate::closure::DependencyRelation::Transitive) => "transitive dependency",
                None => unreachable!("dependency comes from the closure"),
            };
            write_matrix_row(
                &mut output,
                selected.as_str(),
                dependency,
                relation,
                &profile
                    .closure
                    .shortest_path(selected.as_str(), dependency)
                    .expect("reachable dependency has a path"),
                features[dependency],
            );
        }
    }

    output.push_str(
        "\n## Release blockers\n\n\
         | Feature | Relation | Path | Claim | Evidence |\n|---|---|---|---|---|\n",
    );
    for id in &closure {
        let feature = features[id.as_str()];
        if feature.claim_state == crate::ClaimState::Claimed && !feature.evidence.is_empty() {
            continue;
        }
        let selected = source
            .selected_features
            .iter()
            .any(|selected| selected.as_str() == id);
        let path = profile
            .closure
            .shortest_path_from(
                source.selected_features.iter().map(|item| item.as_str()),
                id,
            )
            .expect("closure member has a selected path");
        let relation = if selected {
            "direct selection"
        } else if path.len() == 2 {
            "direct dependency"
        } else {
            "transitive dependency"
        };
        writeln!(
            output,
            "| {id} | {relation} | {} | {} | {} |",
            path.join(" → "),
            claim_name(feature.claim_state),
            crate::validate::dependencies::evidence_state(feature),
        )
        .expect("writing to String cannot fail");
    }

    output.push_str("\n## Dependency-first implementation order\n\n");
    for (position, id) in profile
        .closure
        .dependency_first_order(source.selected_features.iter().map(|item| item.as_str()))
        .iter()
        .enumerate()
    {
        writeln!(output, "{}. `{id}`", position + 1).expect("writing to String cannot fail");
    }
    write!(
        output,
        "\n## Completeness boundary\n\n\
         This report covers only the {} direct all-of relationships imported from Clause 24.7, Table 10 and their {} endpoint features. It does not establish minimum conformance, selected-profile conformance, or complete feature taxonomy coverage.\n\n\
         The alternative-choice requirements for GP01, the minimum graph type, GL04–GL10 scalar families, GV45, and GV65 are not implication edges. M01-PR05 owns those rules.\n",
        source.implications.len(),
        implication_endpoint_count,
    )
    .expect("writing to String cannot fail");
    output
}

fn write_matrix_row(
    output: &mut String,
    source: &str,
    feature_id: &str,
    relation: &str,
    path: &[String],
    feature: &crate::FeatureRecord,
) {
    writeln!(
        output,
        "| {source} | {feature_id} | {relation} | {} | {} | {} | {} |",
        path.join(" → "),
        enum_name(feature.runtime_support),
        claim_name(feature.claim_state),
        crate::validate::dependencies::evidence_state(feature),
    )
    .expect("writing to String cannot fail");
}

fn target_closure(profile: &ValidatedProfile) -> std::collections::BTreeSet<String> {
    profile.closure.closure_for(
        profile
            .profile()
            .selected_features
            .iter()
            .map(|item| item.as_str()),
    )
}

fn enum_name(value: RuntimeSupport) -> &'static str {
    match value {
        RuntimeSupport::Supported => "supported",
        RuntimeSupport::Unsupported => "unsupported",
        RuntimeSupport::Referenced => "referenced",
    }
}

fn claim_name(value: crate::ClaimState) -> &'static str {
    match value {
        crate::ClaimState::Unsupported => "unsupported",
        crate::ClaimState::ImplementedUnclaimed => "implemented_unclaimed",
        crate::ClaimState::ClaimedPendingEvidence => "claimed_pending_evidence",
        crate::ClaimState::Claimed => "claimed",
    }
}

fn claim_name_rust(value: crate::ClaimState) -> &'static str {
    match value {
        crate::ClaimState::Unsupported => "Unsupported",
        crate::ClaimState::ImplementedUnclaimed => "ImplementedUnclaimed",
        crate::ClaimState::ClaimedPendingEvidence => "ClaimedPendingEvidence",
        crate::ClaimState::Claimed => "Claimed",
    }
}

fn runtime_support_rust(value: RuntimeSupport) -> &'static str {
    match value {
        RuntimeSupport::Supported => "Supported",
        RuntimeSupport::Unsupported => "Unsupported",
        RuntimeSupport::Referenced => "Referenced",
    }
}

fn flagger_status_name(iso: bool, direct: bool, runtime_support: RuntimeSupport) -> &'static str {
    if flagger_accepted(iso, direct, runtime_support) {
        "accepted"
    } else {
        "rejected"
    }
}

fn flagger_accepted(iso: bool, direct: bool, runtime_support: RuntimeSupport) -> bool {
    (iso && direct) || runtime_support == RuntimeSupport::Supported
}

fn markdown(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "\\|")
        .replace(['\r', '\n'], " ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn flagger_policy_keeps_admission_independent_from_runtime_support() {
        assert!(flagger_accepted(true, true, RuntimeSupport::Unsupported));
        assert!(flagger_accepted(true, false, RuntimeSupport::Supported));
        assert!(flagger_accepted(false, false, RuntimeSupport::Supported));
        assert!(!flagger_accepted(false, false, RuntimeSupport::Unsupported));
        assert!(!flagger_accepted(false, false, RuntimeSupport::Referenced));
        assert!(!flagger_accepted(true, false, RuntimeSupport::Unsupported));
        assert!(!flagger_accepted(true, false, RuntimeSupport::Referenced));
    }
}
