//! Deterministic checked-in Rust and Markdown generation.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::model::RuntimeSupport;
use crate::{ProfileError, ValidatedProfile, load_profile};

const SOURCE: &str = "spec/gql-profile/profile.json";

/// Render every canonical source and generated output for a validated profile.
pub fn render_outputs(profile: &ValidatedProfile) -> Result<Vec<(PathBuf, String)>, ProfileError> {
    let source = format!("{}\n", serde_json::to_string_pretty(profile.profile())?);
    Ok(vec![
        (PathBuf::from(SOURCE), source),
        (
            PathBuf::from("crates/selene-profile/src/generated/mod.rs"),
            render_mod(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/feature_ids.rs"),
            render_feature_ids(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/feature_data.rs"),
            render_feature_data(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/annex_b.rs"),
            render_annex_b(profile),
        ),
        (
            PathBuf::from("crates/selene-profile/src/generated/profile_data.rs"),
            render_profile_data(profile),
        ),
        (
            PathBuf::from("spec/gql-profile/registry.md"),
            render_markdown(profile),
        ),
        (
            PathBuf::from("docs/gql/conformance/features.md"),
            render_claim_matrix(profile),
        ),
    ])
}

/// Regenerate checked-in source, Rust, and Markdown from the profile JSON.
pub fn write_repository(root: &Path) -> Result<(), ProfileError> {
    let profile = load_profile(&root.join(SOURCE))?;
    for (relative, content) in render_outputs(&profile)? {
        let path = root.join(relative);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|source| ProfileError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        std::fs::write(&path, content).map_err(|source| ProfileError::Io { path, source })?;
    }
    Ok(())
}

/// Fail when a checked-in source or generated output is stale.
pub fn check_repository(root: &Path) -> Result<(), ProfileError> {
    let profile = load_profile(&root.join(SOURCE))?;
    for (relative, expected) in render_outputs(&profile)? {
        let path = root.join(&relative);
        let actual = std::fs::read_to_string(&path).map_err(|source| ProfileError::Io {
            path: path.clone(),
            source,
        })?;
        if actual != expected {
            return Err(ProfileError::Stale(relative));
        }
    }
    Ok(())
}

fn header(profile: &ValidatedProfile) -> String {
    format!(
        "// @generated by `cargo run -p selene-db-profile --bin selene-profile -- --write`; generator-version: {}; profile-hash: {}\n\n",
        profile.profile().generator_version,
        profile.hash(),
    )
}

fn render_mod(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "mod annex_b;\nmod feature_data;\nmod feature_ids;\nmod profile_data;\n\n\
         pub use annex_b::ANNEX_B_REGISTER;\n\
         pub use feature_data::{\n    \
         FLAGGER_ACCEPTED_FEATURES, NOT_SUPPORTED_RATIONALE, REFERENCED_FEATURES, SUPPORTED_FEATURES,\n\
         };\n\
         pub use profile_data::{DIRECT_SELECTED_FEATURES, TARGET_FEATURE_CLOSURE};\n\n",
    );
    writeln!(
        output,
        "/// Source profile format version.\npub const PROFILE_FORMAT_VERSION: u32 = {};",
        profile.profile().format_version
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "/// Source profile generator version.\npub const PROFILE_GENERATOR_VERSION: u32 = {};",
        profile.profile().generator_version
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "/// Stable target profile identifier.\npub const PROFILE_ID: &str = {:?};",
        profile.profile().profile_id
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "/// Whether the target profile is release-claimable.\npub const RELEASE_CLAIMABLE: bool = {};",
        profile.profile().release_claimable
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "/// BLAKE3 hash of the canonical semantic profile.\npub const PROFILE_HASH: &str = {:?};",
        profile.hash()
    )
    .expect("writing to String cannot fail");
    output
}

fn render_feature_ids(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str("use crate::runtime::FeatureId;\n\nimpl FeatureId {\n");
    let mut entries = profile
        .profile()
        .features
        .iter()
        .map(|item| (item.id.as_str(), item.name.as_str()))
        .chain(
            profile
                .profile()
                .implementation_extensions
                .iter()
                .map(|item| (item.id.as_str(), item.name.as_str())),
        )
        .collect::<Vec<_>>();
    entries.sort_unstable();
    for (id, name) in entries {
        writeln!(
            output,
            "    #[doc = {:?}]\n    pub const {id}: FeatureId = FeatureId::new({id:?});",
            format!("`{name}`")
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("}\n");
    output
}

fn render_feature_data(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "use crate::runtime::FeatureId;\n\n\
         /// Every feature and extension currently referenced by runtime consumers.\n\
         #[rustfmt::skip]\n\
         pub const REFERENCED_FEATURES: &[(FeatureId, &str)] = &[\n",
    );
    let mut entries = profile
        .profile()
        .features
        .iter()
        .map(|item| {
            (
                item.runtime_order,
                item.id.as_str(),
                item.name.as_str(),
                item.runtime_support,
                item.unsupported_rationale.as_str(),
            )
        })
        .chain(
            profile
                .profile()
                .implementation_extensions
                .iter()
                .map(|item| {
                    (
                        item.runtime_order,
                        item.id.as_str(),
                        item.name.as_str(),
                        item.runtime_support,
                        item.unsupported_rationale.as_str(),
                    )
                }),
        )
        .collect::<Vec<_>>();
    entries.sort_by_key(|item| item.0);
    for (_, id, name, _, _) in &entries {
        writeln!(output, "    (FeatureId::{id}, {name:?}),")
            .expect("writing to String cannot fail");
    }
    output.push_str(
        "];\n\n/// Existing runtime-supported feature and extension set.\n\
         #[rustfmt::skip]\n\
         pub const SUPPORTED_FEATURES: &[FeatureId] = &[\n",
    );
    for id in &profile.profile().supported_feature_order {
        writeln!(output, "    FeatureId::{},", id.as_str()).expect("writing to String cannot fail");
    }
    output.push_str(
        "];\n\n/// Exact runtime rejection rationales.\n\
         #[rustfmt::skip]\n\
         pub const NOT_SUPPORTED_RATIONALE: &[(FeatureId, &str)] = &[\n",
    );
    for feature_id in &profile.profile().unsupported_feature_order {
        let feature = profile
            .profile()
            .features
            .iter()
            .find(|item| item.id == *feature_id)
            .expect("unsupported compatibility references were validated");
        writeln!(
            output,
            "    (FeatureId::{}, {:?}),",
            feature.id.as_str(),
            feature.unsupported_rationale
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("];\n");
    output.push_str(
        "\n/// Parser-visible compatibility set retained until M01-PR04.\n\
         #[rustfmt::skip]\n\
         pub const FLAGGER_ACCEPTED_FEATURES: &[FeatureId] = &[\n",
    );
    let mut accepted = profile
        .profile()
        .selected_features
        .iter()
        .map(|id| id.as_str())
        .chain(
            profile
                .profile()
                .implementation_extensions
                .iter()
                .filter(|extension| extension.runtime_support == RuntimeSupport::Supported)
                .map(|extension| extension.id.as_str()),
        )
        .collect::<Vec<_>>();
    accepted.sort_unstable();
    for id in accepted {
        writeln!(output, "    FeatureId::{id},").expect("writing to String cannot fail");
    }
    output.push_str("];\n");
    output
}

fn render_annex_b(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "use crate::runtime::{AnnexBId, ImplDefinedChoice};\n\n\
         /// Partial implementation-defined inventory inherited from the 1.x register.\n\
         #[rustfmt::skip]\n\
         pub const ANNEX_B_REGISTER: &[(AnnexBId, ImplDefinedChoice)] = &[\n",
    );
    let mut choices = profile
        .profile()
        .implementation_defined_choices
        .iter()
        .collect::<Vec<_>>();
    choices.sort_by_key(|item| item.runtime_order);
    for item in choices {
        writeln!(
            output,
            "    (AnnexBId::new({:?}), ImplDefinedChoice {{ choice: {:?}, settled_in: {:?} }}),",
            item.id.as_str(),
            item.choice,
            item.settled_in
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("];\n");
    output
}

fn render_profile_data(profile: &ValidatedProfile) -> String {
    let mut output = header(profile);
    output.push_str(
        "use crate::runtime::FeatureId;\n\n\
         /// ISO features selected directly by the target profile.\n\
         #[rustfmt::skip]\n\
         pub const DIRECT_SELECTED_FEATURES: &[FeatureId] = &[\n",
    );
    for id in &profile.profile().selected_features {
        writeln!(output, "    FeatureId::{},", id.as_str()).expect("writing to String cannot fail");
    }
    output.push_str(
        "];\n\n/// Direct selections plus every reachable Table 10 dependency.\n\
         #[rustfmt::skip]\n\
         pub const TARGET_FEATURE_CLOSURE: &[FeatureId] = &[\n",
    );
    for id in profile.closure.closure_for(
        profile
            .profile()
            .selected_features
            .iter()
            .map(|item| item.as_str()),
    ) {
        writeln!(output, "    FeatureId::{id},").expect("writing to String cannot fail");
    }
    output.push_str("];\n");
    output
}

fn render_markdown(profile: &ValidatedProfile) -> String {
    let mut output = format!(
        "<!-- @generated by selene-profile; profile-hash: {} -->\n\n\
         # GQL profile registry\n\n\
         Profile `{}` uses source format {} and generator version {}. Release claimable: **{}**. Runtime support is separate from formal claim state.\n\n\
         ## ISO optional features\n\n\
         | ID | Name | Runtime | Claim | Rationale |\n\
         |---|---|---|---|---|\n",
        profile.hash(),
        markdown(&profile.profile().profile_id),
        profile.profile().format_version,
        profile.profile().generator_version,
        profile.profile().release_claimable,
    );
    for item in &profile.profile().features {
        writeln!(
            output,
            "| {} | {} | {} | {} | {} |",
            item.id.as_str(),
            markdown(&item.name),
            enum_name(item.runtime_support),
            claim_name(item.claim_state),
            markdown(&item.unsupported_rationale)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str(
        "\n## Implementation extensions\n\n\
         These IDs are not ISO optional features.\n\n\
         | ID | Name | Runtime |\n|---|---|---|\n",
    );
    for item in &profile.profile().implementation_extensions {
        writeln!(
            output,
            "| {} | {} | {} |",
            item.id.as_str(),
            markdown(&item.name),
            enum_name(item.runtime_support)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str(
        "\n## Partial implementation-defined inventory\n\n\
         This table preserves the existing incomplete Annex B register. M01-PR03 owns completeness and semantic correction.\n\n\
         | ID | Choice | Existing owner |\n|---|---|---|\n",
    );
    for item in &profile.profile().implementation_defined_choices {
        writeln!(
            output,
            "| {} | {} | {} |",
            item.id.as_str(),
            markdown(&item.choice),
            markdown(&item.settled_in)
        )
        .expect("writing to String cannot fail");
    }
    writeln!(
        output,
        "\nDirect selected features: {}. Complete target closure: {}. Direct implication edges: {}. Implementation-dependent notes: {}. Evidence references: {}.",
        profile.profile().selected_features.len(),
        target_closure(profile).len(),
        profile.profile().implications.len(),
        profile.profile().implementation_dependent_notes.len(),
        profile.profile().evidence.len()
    )
    .expect("writing to String cannot fail");
    output
}

fn render_claim_matrix(profile: &ValidatedProfile) -> String {
    let source = profile.profile();
    let closure = target_closure(profile);
    let implication_endpoint_count = source
        .implications
        .iter()
        .flat_map(|edge| [edge.source.as_str(), edge.target.as_str()])
        .collect::<BTreeSet<_>>()
        .len();
    let claimability = if source.release_claimable {
        "This target is release-claimable under the validated profile contract. Runtime support and formal claim state are reported independently; this status does not establish minimum- or selected-profile conformance."
    } else {
        "This target is not release-claimable. Runtime support and formal claim state are reported independently."
    };
    let features = source
        .features
        .iter()
        .map(|feature| (feature.id.as_str(), feature))
        .collect::<std::collections::BTreeMap<_, _>>();
    let mut output = format!(
        "<!-- @generated by selene-profile; generator-version: {}; profile-hash: {} -->\n\n\
         # GQL conformance features\n\n\
         | Field | Value |\n|---|---|\n\
         | Target profile | `{}` |\n\
         | Source format | {} |\n\
         | Generator version | {} |\n\
         | Profile hash | `{}` |\n\
         | Release claimable | **{}** |\n\
         | Direct selections | {} |\n\
         | Complete Table 10 closure | {} |\n\n\
         {claimability}\n\n\
         ## Direct Table 10 implications\n\n\
         | Source | Dependency | Provenance |\n|---|---|---|\n",
        source.generator_version,
        profile.hash(),
        markdown(&source.profile_id),
        source.format_version,
        source.generator_version,
        profile.hash(),
        source.release_claimable,
        source.selected_features.len(),
        closure.len(),
    );
    let clauses = source
        .clause_anchors
        .iter()
        .map(|anchor| (anchor.id.as_str(), anchor.citation.as_str()))
        .collect::<std::collections::BTreeMap<_, _>>();
    for edge in &source.implications {
        let provenance = edge
            .clause_anchors
            .iter()
            .map(|id| clauses[id.as_str()])
            .collect::<Vec<_>>()
            .join("; ");
        writeln!(
            output,
            "| {} | {} | {} |",
            edge.source.as_str(),
            edge.target.as_str(),
            markdown(&provenance)
        )
        .expect("writing to String cannot fail");
    }

    output.push_str(
        "\n## Claim matrix and dependency paths\n\n\
         | Source | Feature | Relation | Path | Runtime | Claim | Evidence |\n\
         |---|---|---|---|---|---|---|\n",
    );
    for selected in &source.selected_features {
        write_matrix_row(
            &mut output,
            selected.as_str(),
            selected.as_str(),
            "direct selection",
            &[selected.as_str().to_owned()],
            features[selected.as_str()],
        );
        for dependency in profile.closure.dependencies(selected.as_str()) {
            let relation = match profile.closure.relation(selected.as_str(), dependency) {
                Some(crate::closure::DependencyRelation::Direct) => "direct dependency",
                Some(crate::closure::DependencyRelation::Transitive) => "transitive dependency",
                None => unreachable!("dependency comes from the closure"),
            };
            write_matrix_row(
                &mut output,
                selected.as_str(),
                dependency,
                relation,
                &profile
                    .closure
                    .shortest_path(selected.as_str(), dependency)
                    .expect("reachable dependency has a path"),
                features[dependency],
            );
        }
    }

    output.push_str(
        "\n## Release blockers\n\n\
         | Feature | Relation | Path | Claim | Evidence |\n|---|---|---|---|---|\n",
    );
    for id in &closure {
        let feature = features[id.as_str()];
        if feature.claim_state == crate::ClaimState::Claimed && !feature.evidence.is_empty() {
            continue;
        }
        let selected = source
            .selected_features
            .iter()
            .any(|selected| selected.as_str() == id);
        let path = profile
            .closure
            .shortest_path_from(
                source.selected_features.iter().map(|item| item.as_str()),
                id,
            )
            .expect("closure member has a selected path");
        let relation = if selected {
            "direct selection"
        } else if path.len() == 2 {
            "direct dependency"
        } else {
            "transitive dependency"
        };
        writeln!(
            output,
            "| {id} | {relation} | {} | {} | {} |",
            path.join(" → "),
            claim_name(feature.claim_state),
            crate::validate::dependencies::evidence_state(feature),
        )
        .expect("writing to String cannot fail");
    }

    output.push_str("\n## Dependency-first implementation order\n\n");
    for (position, id) in profile
        .closure
        .dependency_first_order(source.selected_features.iter().map(|item| item.as_str()))
        .iter()
        .enumerate()
    {
        writeln!(output, "{}. `{id}`", position + 1).expect("writing to String cannot fail");
    }
    write!(
        output,
        "\n## Completeness boundary\n\n\
         This report covers only the {} direct all-of relationships imported from Clause 24.7, Table 10 and their {} endpoint features. It does not establish minimum conformance, selected-profile conformance, or complete feature taxonomy coverage.\n\n\
         The alternative-choice requirements for GP01, the minimum graph type, GL04–GL10 scalar families, GV45, and GV65 are not implication edges. M01-PR05 owns those rules.\n",
        source.implications.len(),
        implication_endpoint_count,
    )
    .expect("writing to String cannot fail");
    output
}

fn write_matrix_row(
    output: &mut String,
    source: &str,
    feature_id: &str,
    relation: &str,
    path: &[String],
    feature: &crate::FeatureRecord,
) {
    writeln!(
        output,
        "| {source} | {feature_id} | {relation} | {} | {} | {} | {} |",
        path.join(" → "),
        enum_name(feature.runtime_support),
        claim_name(feature.claim_state),
        crate::validate::dependencies::evidence_state(feature),
    )
    .expect("writing to String cannot fail");
}

fn target_closure(profile: &ValidatedProfile) -> std::collections::BTreeSet<String> {
    profile.closure.closure_for(
        profile
            .profile()
            .selected_features
            .iter()
            .map(|item| item.as_str()),
    )
}

fn enum_name(value: RuntimeSupport) -> &'static str {
    match value {
        RuntimeSupport::Supported => "supported",
        RuntimeSupport::Unsupported => "unsupported",
        RuntimeSupport::Referenced => "referenced",
    }
}

fn claim_name(value: crate::ClaimState) -> &'static str {
    match value {
        crate::ClaimState::Unsupported => "unsupported",
        crate::ClaimState::ImplementedUnclaimed => "implemented_unclaimed",
        crate::ClaimState::ClaimedPendingEvidence => "claimed_pending_evidence",
        crate::ClaimState::Claimed => "claimed",
    }
}

fn markdown(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "\\|")
        .replace(['\r', '\n'], " ")
}
