//! Error-rendering corpus entries.

use super::coverage::{
    QuantMethodMirror, VectorErrorKindMirror, VectorMagicMirror, VectorMetricMirror,
    VectorOpMirror, VectorSurface,
};
use super::fixtures::{
    ApiInductionPayload, SyntheticErrorFields, VectorCorpusGraph, VectorQuantizationSpec,
};
use super::{VectorCorpusCategory, VectorCorpusEntry, api_error, cfg, synthetic_error};

const ERROR_SURFACE: &[VectorSurface] = &[VectorSurface::ErrorPath];
const NO_METRICS: &[VectorMetricMirror] = &[];
const NO_OPS: &[VectorOpMirror] = &[];
const NO_MAGICS: &[VectorMagicMirror] = &[];
const NO_QUANT: &[QuantMethodMirror] = &[];
const PQ_QUANT: &[QuantMethodMirror] = &[QuantMethodMirror::Pq];

pub(crate) fn entries() -> Vec<VectorCorpusEntry> {
    use VectorCorpusCategory as C;
    use VectorCorpusGraph as G;
    use VectorErrorKindMirror as E;
    use VectorMagicMirror as X;
    use VectorMetricMirror as M;
    use VectorOpMirror as O;
    use VectorQuantizationSpec as Z;

    vec![
        VectorCorpusEntry {
            slug: "error-invalid-config",
            description: "InvalidConfig from zero-dimensional HNSW config.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(E::InvalidConfig, ApiInductionPayload::InvalidConfigZeroDim),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::InvalidConfig],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-dimension-mismatch",
            description: "Synthetic DimensionMismatch shape.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: synthetic_error(
                E::DimensionMismatch,
                SyntheticErrorFields::DimensionMismatch,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::DimensionMismatch],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-section-decode-failed",
            description: "Synthetic SectionDecodeFailed shape.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: synthetic_error(
                E::SectionDecodeFailed,
                SyntheticErrorFields::SectionDecodeFailed,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::SectionDecodeFailed],
            covered_magics: &[X::Vgrp],
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-section-encode-failed",
            description: "Synthetic SectionEncodeFailed shape.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: synthetic_error(
                E::SectionEncodeFailed,
                SyntheticErrorFields::SectionEncodeFailed,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::SectionEncodeFailed],
            covered_magics: &[X::Vvec],
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-invalid-node-id",
            description: "InvalidNodeId from NodeId::TOMBSTONE.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(
                E::InvalidNodeId,
                ApiInductionPayload::InvalidNodeIdTombstone,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: &[O::Insert],
            covered_errors: &[E::InvalidNodeId],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-dimensions-locked",
            description: "DimensionsLocked from wrong-dimensional search.",
            graph: G::SingleOriginCosine,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(
                E::DimensionsLocked,
                ApiInductionPayload::DimensionsLockedSearch,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: &[M::Cosine],
            covered_ops: NO_OPS,
            covered_errors: &[E::DimensionsLocked],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-invalid-payload",
            description: "InvalidPayload from empty bulk payload.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(
                E::InvalidPayload,
                ApiInductionPayload::InvalidPayloadEmptyBulk,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::InvalidPayload],
            covered_magics: &[X::Vecb],
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-encode-failed",
            description: "Synthetic EncodeFailed shape.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: synthetic_error(E::EncodeFailed, SyntheticErrorFields::EncodeFailed),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::EncodeFailed],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-operation-update-not-supported",
            description: "OperationNotSupportedYet from reserved Update op.",
            graph: G::SingleOriginCosine,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(
                E::OperationNotSupportedYet,
                ApiInductionPayload::OperationUpdate,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: &[O::Update],
            covered_errors: &[E::OperationNotSupportedYet],
            covered_magics: &[X::Vecu],
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-operation-delete-not-supported",
            description: "OperationNotSupportedYet from reserved Delete op.",
            graph: G::SingleOriginCosine,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(
                E::OperationNotSupportedYet,
                ApiInductionPayload::OperationDelete,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: &[O::Delete],
            covered_errors: &[E::OperationNotSupportedYet],
            covered_magics: &[X::Vecu],
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-duplicate-node-id",
            description: "DuplicateNodeId from re-inserting an existing node.",
            graph: G::SingleOriginCosine,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(E::DuplicateNodeId, ApiInductionPayload::DuplicateNodeId),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: &[O::Insert],
            covered_errors: &[E::DuplicateNodeId],
            covered_magics: &[X::Vecu],
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-non-finite-vector",
            description: "NonFiniteVectorComponent from a NaN vector component.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(
                E::NonFiniteVectorComponent,
                ApiInductionPayload::NonFiniteVector,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: &[O::Insert],
            covered_errors: &[E::NonFiniteVectorComponent],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-internal-index-exhausted",
            description: "Synthetic InternalIndexExhausted shape.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: synthetic_error(
                E::InternalIndexExhausted,
                SyntheticErrorFields::InternalIndexExhausted,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::InternalIndexExhausted],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-max-layer-exceeds-cap",
            description: "MaxLayerExceedsCap from a direct HNSW insertion.",
            graph: G::Empty,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(
                E::MaxLayerExceedsCap,
                ApiInductionPayload::MaxLayerExceedsCap,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: &[O::Insert],
            covered_errors: &[E::MaxLayerExceedsCap],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-non-finite-query",
            description: "NonFiniteQueryComponent from a NaN query component.",
            graph: G::SingleOriginCosine,
            config: cfg(4, M::Cosine, Z::DISABLED),
            invocation: api_error(
                E::NonFiniteQueryComponent,
                ApiInductionPayload::NonFiniteQuery,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: &[M::Cosine],
            covered_ops: NO_OPS,
            covered_errors: &[E::NonFiniteQueryComponent],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-pq-training-deferred",
            description: "Synthetic PqTrainingDeferred shape.",
            graph: G::Empty,
            config: cfg(8, M::L2, Z::DISABLED),
            invocation: synthetic_error(
                E::PqTrainingDeferred,
                SyntheticErrorFields::PqTrainingDeferred,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::PqTrainingDeferred],
            covered_magics: NO_MAGICS,
            covered_quant_methods: PQ_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-pq-dimension-not-divisible",
            description: "PqDimensionNotDivisible from invalid PQ config.",
            graph: G::Empty,
            config: cfg(8, M::L2, Z::DISABLED),
            invocation: api_error(
                E::PqDimensionNotDivisible,
                ApiInductionPayload::PqDimensionNotDivisible,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::PqDimensionNotDivisible],
            covered_magics: NO_MAGICS,
            covered_quant_methods: PQ_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-ivf-training-deferred",
            description: "Synthetic IvfTrainingDeferred shape.",
            graph: G::Empty,
            config: cfg(8, M::L2, Z::DISABLED),
            invocation: synthetic_error(
                E::IvfTrainingDeferred,
                SyntheticErrorFields::IvfTrainingDeferred,
            ),
            category: C::Error,
            covered_surfaces: &[
                VectorSurface::IvfBuild,
                VectorSurface::IvfSearchUnfiltered,
                VectorSurface::IvfRecovery,
                VectorSurface::ErrorPath,
            ],
            covered_metrics: &[M::L2],
            covered_ops: NO_OPS,
            covered_errors: &[E::IvfTrainingDeferred],
            covered_magics: &[X::Vivf, X::Vcqb, X::Vipb, X::Vpos],
            covered_quant_methods: PQ_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-ivf-dimension-mismatch",
            description: "Synthetic IvfDimensionMismatch shape.",
            graph: G::Empty,
            config: cfg(8, M::L2, Z::DISABLED),
            invocation: synthetic_error(
                E::IvfDimensionMismatch,
                SyntheticErrorFields::IvfDimensionMismatch,
            ),
            category: C::Error,
            covered_surfaces: &[VectorSurface::IvfSearchFiltered, VectorSurface::ErrorPath],
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::IvfDimensionMismatch],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-ivf-invalid-nprobe",
            description: "Synthetic IvfInvalidNProbe shape.",
            graph: G::Empty,
            config: cfg(8, M::L2, Z::DISABLED),
            invocation: synthetic_error(
                E::IvfInvalidNProbe,
                SyntheticErrorFields::IvfInvalidNProbe,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::IvfInvalidNProbe],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-ivf-section-inconsistent",
            description: "Synthetic IvfSectionInconsistent shape.",
            graph: G::Empty,
            config: cfg(8, M::L2, Z::DISABLED),
            invocation: synthetic_error(
                E::IvfSectionInconsistent,
                SyntheticErrorFields::IvfSectionInconsistent,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::IvfSectionInconsistent],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-ivf-training-failed",
            description: "Synthetic IvfTrainingFailed shape.",
            graph: G::Empty,
            config: cfg(8, M::L2, Z::DISABLED),
            invocation: synthetic_error(
                E::IvfTrainingFailed,
                SyntheticErrorFields::IvfTrainingFailed,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::IvfTrainingFailed],
            covered_magics: NO_MAGICS,
            covered_quant_methods: NO_QUANT,
        },
        VectorCorpusEntry {
            slug: "error-pq-codebook-train-failed",
            description: "Synthetic PqCodebookTrainFailed shape.",
            graph: G::Empty,
            config: cfg(8, M::L2, Z::DISABLED),
            invocation: synthetic_error(
                E::PqCodebookTrainFailed,
                SyntheticErrorFields::PqCodebookTrainFailed,
            ),
            category: C::Error,
            covered_surfaces: ERROR_SURFACE,
            covered_metrics: NO_METRICS,
            covered_ops: NO_OPS,
            covered_errors: &[E::PqCodebookTrainFailed],
            covered_magics: NO_MAGICS,
            covered_quant_methods: PQ_QUANT,
        },
    ]
}
